### PR TITLE
feat: Overlay

### PR DESCRIPTION
**Pull request by lenianiva**
- feat: Add Lean4 overlay
- feat: Supports custom overlay versions

The overlay is a more robust way to use Lean, and it supports having multiple Lean versions simultaneously.

### CODE REVIEW

**Comment by wuyoli** [comment]
you could add your example directly in the flake template.

**Comment by lenianiva** [comment]
> you could add your example directly in the flake template.

I mainly want it to be there so I can `nix flake check` it

**Comment by lenianiva** [comment]
I could not find out how `lake` parses `lean-toolchain`, so currently I have a solution that works for GitHub repositories:
```nix
builtins.match "(.*)\/([^:]*)(:.*)?" "leanprover/lean4:v4.12.0"
```
gives
```nix
[
  "leanprover"
  "lean4"
  ":v4.12.0"
]
```

**Comment by lenianiva** [comment]
Overlay parameterization is done. Now we need to have a list of manifest files corresponding to each Lean4 tag and this is mostly a chore

**Pull request merged**
