### PR TITLE
feat: Manifest for v4.14.0

### PR DESCRIPTION
**Pull request by lenianiva**
Pending testing

### CODE REVIEW

**Comment by lenianiva** [comment]
Aesop doesn't build. Strange

**Comment by stepbrobd** [comment]
it builds after rebasing on top of #31

**Comment by lenianiva** [comment]
> it builds after rebasing on top of #31

Not on `x86_64-linux`

**Comment by lenianiva** [comment]
Solved building problem on `x86_64-linux`. Should be ready to merge.

**Pull request merged**
