### PR TITLE
refactor: Add code formatting and remove hacks

### PR DESCRIPTION
**Pull request by stepbrobd**
- added `nixpkgs-fmt` and reformatted the codebase with it
- added `systems` to inputs, making outputs overridable
- instead of using expensive `with pkgs;`, packages used in `lib/packages.nix` should refer to the ones listed in the argument section (provided with `callPackage`)

I'll take a look into https://github.com/lenianiva/lean4-nix/issues/5#issuecomment-2460718642 in a bit

### CODE REVIEW

**Comment by lenianiva** [comment]
Does it compile on Darwin for v4.12?

**Comment by lenianiva** [comment]
I'll migrate bit by bit to main.

**Comment by lenianiva** [comment]
Can we break this PR into bits and merge them one by one? e.g. we could get the formatting and systems part in first, and then we can bring in the optimizations.

**Comment by stepbrobd** [comment]
`nix flake check` passes on aarch64-darwin

**Comment by lenianiva** [comment]
`nix flake check` passes on `x86_64-linux`.

**Comment by lenianiva** [comment]
I need to configure the linter a bit. I don't like the default formatting.

**Comment by stepbrobd** [comment]
> I need to configure nixfmt a bit. I don't like the default formatting.

change `nixpkgs-fmt` to `nixfmt-rfc-style`?

**Comment by stepbrobd** [comment]
Superseded by #31

**Pull request closed without merging**
